"""Type stubs for real_ladybug (KuzuDB Python bindings)."""

from typing import Any

class Database:
    def __init__(self, path: str) -> None: ...

class Connection:
    def __init__(self, db: Database) -> None: ...
    def execute(self, query: str, parameters: dict[str, Any] | None = None) -> QueryResult: ...

class QueryResult:
    def get_all(self) -> list[list[Any]]: ...
    def get_next(self) -> list[Any]: ...
    def has_next(self) -> bool: ...
    def get_num_tuples(self) -> int: ...
    def get_column_names(self) -> list[str]: ...
    def close(self) -> None: ...
    def reset_iterator(self) -> None: ...
